config/routes.rb
Rails.application.routes.draw do
  get "static_pages/about"

  # root "tests#index"

  resources :tests do
    resources :questions, shallow: true
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_answers_count, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_answers_count
    if question.answers.count >= 4
      errors.add(:question, "Too many answers! (must be less than 5)")
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope -> { order(title: :asc) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: "author_id"
  belongs_to :category

  has_many :test_results, dependent: :destroy
  has_many :users, through: :test_results
  has_many :questions, dependent: :destroy

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :easy, -> { where(level: [ 0, 1 ]) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where("level >= ?", 5) }
  scope :by_level, ->(level) { where(level: level) }
  scope :by_category_name, ->(category_name) {
    joins(:category)
      .where(categories: { title: category_name })
      .order(title: :desc)
  }

  # Добавил отдельный метод для получения массива заголовков с плак
  def self.titles_by_category(category_name)
    by_category_name(category_name).pluck(:title)
  end
end

app/models/test_result.rb
class TestResult < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/user.rb
class User < ApplicationRecord
  has_many :test_results, dependent: :destroy
  has_many :tests, through: :test_results, dependent: :destroy
  has_many :author_tests, class_name: "Test", foreign_key: "author_id"

  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  def tests_by_level(level)
    tests.by_level(level)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :set_answer, only: %i[show edit update destroy]
  before_action :set_question, only: %i[new create]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to @answer
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    format.html { redirect_to @answer.question }
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_test, only: %i[index new create]
  before_action :set_question, only: %i[show destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def index
    @questions = @test.questions
    render plain: @questions.map(&:content).join("\n")
  end

  def show
    render plain: @question.content.to_s
  end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      render plain: "Question created successfully! ID: #{@question.id}, Content: #{@question.content}"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @question.destroy
    render plain: "Question deleted successfully!"
  end

  private

  def question_params
    params.require(:question).permit(:content)
  end

  def set_test
    @test = Test.find(params[:test_id])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def rescue_with_question_not_found
    render plain: "Question not found!", status: 404
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

  def index
    result = [ "Class: #{params.class}", "Parameters: #{params.inspect}" ]

    render plain: result.join("\n")
  end

  def show
    title = Test.first.title

    render inline: "<%= @test.title %>"
  end

  def new
  end

  def create
    @test = Test.new(test_params)
    if @test.save
      render plain: "Test created successfully! ID: #{@test.id}, Title: #{@test.title}, Level: #{@test.level}"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def test_params
    params.require(:test).permit(:title, :level)
  end


  def rescue_with_test_not_found
    render plain: "Test was not found"
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/answers/_answers.html.erb
<tr>
  <td><%= answer.body %></td>
  <td><%= answer.correct %></td>
  <td><%= link_to 'Show', answer %></td>
  <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
  <td><%= link_to 'Destroy', answer, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/answers/_form.html.erb
<%= form_with model: [@question, @answer], local: true do |f| %>
  <%= render 'shared/errors', resource: @answer %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, id: :answer_body %>
  </div>

  <div class="field">
    <%= f.label :correct %>
    <%= f.check_box :correct, id: :answer_correct %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render 'form', answer: @answer %>

<%= link_to 'Back to Question', question_path(@answer.question) %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<p>
  <%= @question.body %>
</p>

<%= render 'form', answer: @answer %>

<%= link_to 'Back to Question', question_path(@question) %>

app/views/answers/show.html.erb
<h1>Question</h1>

<p>
  <%= @answer.question.body %>
</p>

<p>
  <strong>Answers body:</strong>
  <%= @answer.body %>
</p>

<p>
  <strong>Answer is correct?</strong>
  <%= @answer.correct %>
</p>

<%= link_to 'Edit answer', edit_answer_path(@answer) %> |

<%= link_to 'Back to Question', question_path(@answer.question) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "The Guru Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/index.html.erb
<h1>Test data: time is: <%= Time.now %> </h1>

app/views/questions/new.html.erb
<h1>Create a New Question</h1>

<%= form_with model: @question, url: test_questions_path(@test), method: :post do |f| %>
  <div>
    <%= f.label :content, "Question" %>
    <%= f.text_field :content %>
  </div>

  <%= f.hidden_field :test_id, value: @test.id %>

  <%= f.submit "Create" %>
<% end %>

app/views/questions/show.html.erb
<%= @question.body %>

<p>
<table>
  <tr><th>Answer</th><th>Correct</th><th colspan=3>Actions</th></tr>
  <%= render @question.answers %>
</table>
</p>

<%= link_to 'New Answer', new_question_answer_path(@question) %> |
<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back to Test', @question.test %>